#if NET7_0_OR_GREATER
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
#endif

namespace KurzSharp.Templates.GrpcApi;

// NOTE: Placeholder for Code Generated by Grpc Tools
public class PlaceholderModelProtoService
{
    public class PlaceholderModelProtoServiceBase
    {
#if NET7_0_OR_GREATER
        public virtual Task<PlaceholderModelDtosResponse> GetProducts(Empty request, ServerCallContext context) =>
            Task.FromResult(new PlaceholderModelDtosResponse());

        public virtual Task<PlaceholderModelDtosResponse> AddProduct(KurzSharp.GrpcApi.PlaceholderModelDto request,
            ServerCallContext context) => Task.FromResult(new PlaceholderModelDtosResponse());

        public virtual Task<PlaceholderModelDtosResponse> DeleteProduct(KurzSharp.GrpcApi.PlaceholderModelDto request,
            ServerCallContext context) => Task.FromResult(new PlaceholderModelDtosResponse());

        public virtual Task<PlaceholderModelDtosResponse> UpdateProduct(KurzSharp.GrpcApi.PlaceholderModelDto request,
            ServerCallContext context) => Task.FromResult(new PlaceholderModelDtosResponse());
#endif
    }
}
